In [1]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\asus\anaconda3\lib\site-packages (8.0.29)
Requirement already satisfied: protobuf>=3.0.0 in c:\users\asus\anaconda3\lib\site-packages (from mysql-connector-python) (3.19.1)

In [2]:
import mysql.connector
import os
from mysql.connector import Error
import pandas as pd
from datetime import datetime, timedelta

In [3]:
db = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="dhiyaanrn",
  database="db_lms"
)

now = datetime.now()

In [ ]:
def daftar_user(db):
    userName = input("Masukkan nama user: ")
    birthdate = input("Masukkan tanggal lahir (YYYY-MM-DD): ")
    occupation = input("Pekerjaan: ")
    address = input("Masukkan alamat: ")
    val = (userName, birthdate, occupation, address)
    cursor = db.cursor()
    sql = "INSERT INTO users (userName, birthdate, occupation, address) VALUES (%s, %s, %s, %s)"
    cursor.execute(sql, val)
    db.commit()
    print("{} Data berhasil ditambahkan!".format(cursor.rowcount))

def show_user(db):
    cursor = db.cursor()
    sql = "SELECT * FROM users"
    cursor.execute(sql)
    results = cursor.fetchall()
    
    if cursor.rowcount == 0:
        print("Tidak ada data")
    else:
        for data in results:
            print(data)

def daftar_buku(db):
    id_book = int(input("Masukkan kode buku: "))
    bookName = input("Enter book name: ")
    category = input("Masukkan kategori buku: ")
    stock = int(input("Stok buku: "))
    val = (id_book, bookName, category, stock)
    cursor = db.cursor()
    sql = "INSERT INTO books (id_book, bookName, category, stock) VALUES (%s, %s, %s, %s) "
    cursor.execute (sql, val)
    db.commit()
    print("{} Data berhasil ditambahkan!".format(cursor.rowcount))

def show_book(db):
    cursor = db.cursor()
    sql = "SELECT * FROM books"
    cursor.execute(sql)
    results = cursor.fetchall()
    
    if cursor.rowcount == 0:
        print("Tidak ada data")
    else:
        for data in results:
            print(data)

def pinjam_buku(db):
    userName = input("Masukkan nama user: ")
    id_book = int(input("Masukkan kode buku: "))
    bookName = input("Enter book name: ")
    borrowDate = now
    returnDate = now + timedelta(2)
    val = (userName, id_book, bookName, borrowDate, returnDate)
    cursor = db.cursor()
    sql = "INSERT INTO borrows (userName, id_book, bookName, borrowDate, returnDate)  VALUES (%s, %s, %s, %s, %s)"
    cursor.execute (sql, val)
    db.commit()
    print("{} Data berhasil ditambahkan!".format(cursor.rowcount))

def show_datapinjam(db):
    cursor = db.cursor()
    sql = "SELECT * FROM borrows"
    cursor.execute(sql)
    results = cursor.fetchall()
    
    if cursor.rowcount == 0:
        print("Tidak ada data")
    else:
        for data in results:
            print(data)
            
def return_book(db):
    id_user = input("Masukkan id peminjam: ")
    id_book = input("Masukkan id buku: ")
    val = (id_user, id_book)
    cursor = db.cursor()
    sql = "DELETE FROM borrows WHERE id_book = '%s'" % (id_book)
    cursor.execute(sql)
    db.commit()
    print("{} Buku berhasil dikembalikan!".format(cursor.rowcount))
                                                
def cari_buku(db):
    bookName = input("Masukkan judul buku: ")
    cursor = db.cursor()
    val = (bookName)
    sql = "select * from books where bookName = '%s'" % (bookName)
    cursor.execute(sql)
    results = cursor.fetchall()
    
    if cursor.rowcount == 0:
        print("Tidak ada data")
    else:
        for data in results:
            print(data)

def show_menu(db):
    print("............APLIKASI DATABASE PYTHON............")
    print("1. Pendaftaran User Baru")
    print("2. Pendaftaran Buku Baru")
    print("3. Peminjaman")
    print("4. Tampilkan Daftar Buku")
    print("5. Tampilkan Daftar User")
    print("6. Tampilkan Daftar Peminjam")
    print("7. Cari Buku")
    print("8. Pengembalian")
    print("9. Exit")
    print("...................................")
    menu = input("Masukkan nomor tugas: ")

    os.system("clear")

    if menu == "1":
        daftar_user(db)
    elif menu == "2":
        daftar_buku(db)
    elif menu == "3":
        pinjam_buku(db)
    elif menu == "4":
        show_book(db)
    elif menu == "5":
        show_user(db)
    elif menu == "6":
        show_datapinjam(db)
    elif menu == "7":
        cari_buku(db)
    elif menu == "8":
        return_book(db)
    elif menu == "9":
        exit()
    else:
        print("Menu Salah!")
        
if __name__ == "__main__":
    while(True):
        show_menu(db)

............APLIKASI DATABASE PYTHON............
1. Pendaftaran User Baru
2. Pendaftaran Buku Baru
3. Peminjaman
4. Tampilkan Daftar Buku
5. Tampilkan Daftar User
6. Tampilkan Daftar Peminjam
7. Cari Buku
8. Pengembalian
9. Exit
...................................
Masukkan nomor tugas: 6
(None, 1000, 'Dodo', 'Belajar Python', datetime.date(2022, 7, 24), None)
(None, 1002, 'Celsi', 'Laut Bercerita', datetime.date(2022, 7, 24), datetime.date(2022, 7, 26))
............APLIKASI DATABASE PYTHON............
1. Pendaftaran User Baru
2. Pendaftaran Buku Baru
3. Peminjaman
4. Tampilkan Daftar Buku
5. Tampilkan Daftar User
6. Tampilkan Daftar Peminjam
7. Cari Buku
8. Pengembalian
9. Exit
...................................
Masukkan nomor tugas: 8
Masukkan id peminjam: 1
Masukkan id buku: 1000
1 Buku berhasil dikembalikan!
............APLIKASI DATABASE PYTHON............
1. Pendaftaran User Baru
2. Pendaftaran Buku Baru
3. Peminjaman
4. Tampilkan Daftar Buku
5. Tampilkan Daftar User
6. Tampilkan Daftar Peminjam
7. Cari Buku
8. Pengembalian
9. Exit
...................................
Masukkan nomor tugas: 6
(None, 1002, 'Celsi', 'Laut Bercerita', datetime.date(2022, 7, 24), datetime.date(2022, 7, 26))
............APLIKASI DATABASE PYTHON............
1. Pendaftaran User Baru
2. Pendaftaran Buku Baru
3. Peminjaman
4. Tampilkan Daftar Buku
5. Tampilkan Daftar User
6. Tampilkan Daftar Peminjam
7. Cari Buku
8. Pengembalian
9. Exit
...................................